# Makefile for clock.c
#
# tim cheadle
# tcheadle@gmu.edu
#
# $Id: Makefile,v 1.1 2003-02-06 05:53:51 session Exp $
#
GCC = gcc
CFLAGS = -lGL -lglut

all: teapot.c
	${GCC} ${CFLAGS} teapot.c -o teapot

clean:
	rm -fr teapot core
