# Makefile for room.c
#
# tim cheadle
# tcheadle@gmu.edu
#
# $Id: Makefile,v 1.1 2002-11-21 05:44:57 session Exp $
#
GCC = gcc
CFLAGS = -lGL -lglut

all: room.c
	${GCC} ${CFLAGS} room.c -o room

clean:
	rm -fr room core
