# Makefile for clock.c
#
# tim cheadle
# tcheadle@gmu.edu
#
# $Id: Makefile,v 1.2 2002-09-24 06:03:48 session Exp $
#
GCC = gcc
CFLAGS = -lGL -lglut

all: clock.c
	${GCC} ${CFLAGS} clock.c -o clock

clean:
	rm -fr clock core
