# Makefile for pinnochio.c
#
# tim cheadle
# tcheadle@gmu.edu
#
# $Id: Makefile,v 1.1 2002-10-13 18:21:34 session Exp $
#
GCC = gcc
CFLAGS = -lGL -lglut

all: pinnochio.c
	${GCC} ${CFLAGS} pinnochio.c -o teapot

clean:
	rm -fr pinnochio core
