# Makefile for pinocchio.c
#
# tim cheadle
# tcheadle@gmu.edu
#
# $Id: Makefile,v 1.2 2002-10-15 06:48:28 session Exp $
#
GCC = gcc
CFLAGS = -lGL -lglut

all: pinocchio.c
	${GCC} ${CFLAGS} pinocchio.c -o pinocchio

clean:
	rm -fr pinocchio core
