SRC_FILES = src/Process.java
			src/Scheduler.java
			src/FCFSScheduler.java
			src/SJFScheduler.java
			src/SRTFScheduler.java
			src/Simulation.java
			
build: ${SRC_FILES}
	java -d build/ ${SRC_FILES}